### ISSUE TITLE
Use orginal tsv to download wav files or use the reformatted version?

### ISSUE THREAD

**Issue by Ryuk17** [bakhtos/GoogleAudioSetScripts#1]
Thanks for your sharing first. I feel confused when running audioset_download.py. Which tsv should I use, the original tsv or the reformatted version in [GoogleAudioSetReformatted](https://github.com/bakhtos/GoogleAudioSetReformatted)?

**Comment by bakhtos** [comment]
Hello!
Sorry for the confusion - the reformatted version is required for functions in `audioset_scripts.py`, to download the audios with `audioset_download.py` you need to make a file listing all necessary files (segments) line by line, like this (also look at `train_list.txt` and `eval_list.txt`):
```
--4gqARaEJE_0
-0BIyqJj9ZU_30000
-0jeONf82dE_21000
```

Other examples are [train_list.txt](train_list.txt)
The scripts will then download the videos with given YouTube-ids (before the last underscore) and trim the 10s interval starting with the time given after the underscore (time in ms).
